mariadb:
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: gp3
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
  auth:
    existingSecret: mariadb

persistence:
  enabled: true
  size: 8Gi
  storageClass: gp3

existingSecret: wordpress

service:
  type: ClusterIP

image:
  registry: docker.io
  repository: bitnamilegacy/wordpress

global:
  security:
    allowInsecureImages: true

ingress:
  enabled: true
  ingressClassName: alb
  pathType: Prefix
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    # hostname, certificate-arn and group.name are injected by wordpress-ingress.yaml.gotmpl
