repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: external-dns-official
    url: https://kubernetes-sigs.github.io/external-dns/

environments:
  default:
    values:
      - cluster_name: k8s-test
        region: us-east-1

---
releases:
  - name: storage
    namespace: kube-system
    chart: ./charts/storage

  - name: external-secrets
    namespace: external-secrets
    createNamespace: true
    chart: external-secrets/external-secrets
    version: 0.10.7
    values:
      - ./values/external-secrets.yaml.gotmpl
    hooks:
      - events: ["postsync"]
        command: kubectl
        args:
          - rollout
          - status
          - deployment/external-secrets-webhook
          - -n
          - external-secrets
          - --timeout=120s

  - name: secrets
    namespace: apps
    createNamespace: true
    chart: ./charts/secrets
    needs:
      - external-secrets/external-secrets
    values:
      - ./values/secrets.yaml

  - name: aws-load-balancer-controller
    namespace: kube-system
    chart: eks/aws-load-balancer-controller
    version: 1.8.3
    needs:
      - kube-system/storage
    values:
      - ./values/alb-controller.yaml.gotmpl
    hooks:
      - events: ["postsync"]
        command: kubectl
        args:
          - rollout
          - status
          - deployment/aws-load-balancer-controller
          - -n
          - kube-system
          - --timeout=120s

  - name: external-dns
    namespace: kube-system
    chart: external-dns-official/external-dns
    version: 1.15.0
    needs:
      - kube-system/storage
    values:
      - ./values/external-dns.yaml.gotmpl

  - name: backend
    namespace: apps
    createNamespace: true
    chart: ./charts/backend

  - name: frontend
    namespace: apps
    createNamespace: true
    chart: ./charts/frontend
    needs:
      - backend

  - name: wordpress
    namespace: apps
    createNamespace: true
    chart: bitnami/wordpress
    version: 22.4.17
    needs:
      - kube-system/storage
      - apps/secrets
      - kube-system/aws-load-balancer-controller
      - kube-system/external-dns
    values:
      - ./values/wordpress.yaml
      - ./values/wordpress-ingress.yaml.gotmpl

  - name: apex-redirect
    namespace: apps
    chart: ./charts/apex-redirect
    needs:
      - kube-system/aws-load-balancer-controller
      - apps/wordpress
    values:
      - ./values/apex-redirect.yaml.gotmpl
