repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: eks
    url: https://aws.github.io/eks-charts

environments:
  default:
    values:
      - cluster_name: k8s-test
        region: us-east-1

releases:
  - name: storage
    namespace: kube-system
    chart: ./charts/storage

  - name: external-secrets
    namespace: external-secrets
    createNamespace: true
    chart: external-secrets/external-secrets
    version: 0.10.7
    values:
      - serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: '{{ awsssm (printf "/%s/eso-role-arn" .Environment.Values.cluster_name) }}'
    hooks:
      - events: ["postsync"]
        command: kubectl
        args:
          - rollout
          - status
          - deployment/external-secrets-webhook
          - -n
          - external-secrets
          - --timeout=120s

  - name: secrets
    namespace: apps
    createNamespace: true
    chart: ./charts/secrets
    needs:
      - external-secrets/external-secrets
    values:
      - ./values/secrets.yaml

  - name: aws-load-balancer-controller
    namespace: kube-system
    chart: eks/aws-load-balancer-controller
    version: 1.8.3
    needs:
      - kube-system/storage
    values:
      - clusterName: {{ .Environment.Values.cluster_name }}
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: '{{ awsssm (printf "/%s/alb-controller-role-arn" .Environment.Values.cluster_name) }}'

  - name: backend
    namespace: apps
    createNamespace: true
    chart: ./charts/backend

  - name: frontend
    namespace: apps
    createNamespace: true
    chart: ./charts/frontend
    needs:
      - backend

  - name: wordpress
    namespace: apps
    createNamespace: true
    chart: bitnami/wordpress
    version: 22.4.17
    needs:
      - kube-system/storage
      - apps/secrets
      - kube-system/aws-load-balancer-controller
    values:
      - ./values/wordpress.yaml
      - ingress:
          annotations:
            alb.ingress.kubernetes.io/certificate-arn: '{{ awsssm (printf "/%s/certificate-arn" .Environment.Values.cluster_name) }}'
